---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  containers:
    - name: flask-container
      image: flask-app:latest
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
