apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask-container
      image: nj1002/devsecops-project:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5
