name: DevSecOps CI Pipeline - Strict Security

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- PHASE DE BUILD ---
      - name: Build Docker image
        run: docker build -t flask-app .

      # --- PHASE DE QUALITÉ (LINT) ---
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint Kubernetes YAML
        run: yamllint k8s.yaml

      # --- PHASE DE SÉCURITÉ TRIVY (SCA & IMAGE) ---
      - name: Scan filesystem with Trivy (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1' # Bloque le pipeline si vulnérabilités trouvées
          severity: 'CRITICAL,HIGH'

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-app
          format: 'table'
          exit-code: '1' # Bloque si l'image contient des failles système
          severity: 'CRITICAL,HIGH'

      # --- PHASE DE CONFORMITÉ CONFTEST (POLICY-AS-CODE) ---
      - name: Test Politique Sécurité (Conftest)
        uses: instrumenta/conftest-action@master
        with:
          files: k8s.yaml
          policy: policy/
          # Conftest bloquera automatiquement si une règle "deny" est déclenchée
