name: CI DevSecOps Pipeline

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build de l'image Docker
        run: docker build -t flask-app:${{ github.sha }} .

      - name: Scan Trivy (Système de fichiers)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0' # On ne bloque pas encore le pipeline pour voir les logs
          severity: 'CRITICAL,HIGH'

      - name: Scan Trivy (Image Docker)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
      
      - name: Test Politique Sécurité (Conftest)
        uses: instrumenta/conftest-action@master
        with:
          files: deployment.yaml
          policy: policy
